# Generated by Django 6.0 on 2026-03-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='eligibility_status',
            field=models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('PENDING', 'Pending Approval'), ('REJECTED', 'Rejected')], default='ELIGIBLE', max_length=20),
        ),
        migrations.AddField(
            model_name='donor',
            name='health_issue_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
