# Generated by Django 4.2.7 on 2026-08-24 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests_app', '0002_bloodrequest_donor_bloodrequest_rejection_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('AUTOMATIC', 'Automatic (System Request)'), ('MANUAL_ADMIN', 'Manual Staff Trigger')], default='AUTOMATIC', max_length=20)),
                ('requested_blood_group', models.CharField(max_length=10)),
                ('units_requested', models.PositiveIntegerField()),
                ('stock_available', models.PositiveIntegerField(default=0)),
                ('compatible_blood_groups', models.CharField(max_length=255)),
                ('eligible_donors_found', models.PositiveIntegerField(default=0)),
                ('donors_notified_count', models.PositiveIntegerField(default=0)),
                ('reasoning_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_logs', to='requests_app.bloodrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
