# Generated by Django 4.2.7 on 2026-08-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_bloodrequest_donor_bloodrequest_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='patient_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='patient_gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='patient_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='patient_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='prescription_document',
            field=models.FileField(blank=True, help_text="Doctor's prescription image or PDF document", null=True, upload_to='prescriptions/'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='purpose',
            field=models.TextField(blank=True, help_text='Purpose of blood request (e.g. Surgery, Accident, Anemia)', null=True),
        ),
    ]
