# Generated by Django 6.0 on 2026-04-01 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_otp_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(choices=[('q1', 'What is the name of your first pet?'), ('q2', "What is your mother's maiden name?"), ('q3', 'What was the name of your first school?'), ('q4', 'What is your favourite childhood movie?'), ('q5', 'What city were you born in?'), ('q6', 'What is the middle name of your oldest sibling?'), ('q7', 'What was the make of your first car?'), ('q8', 'What was the name of your childhood best friend?')], max_length=10)),
                ('answer_hash', models.CharField(max_length=255)),
                ('reset_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='OTPRecord',
        ),
    ]
