# Generated by Django 6.0.2 on 2026-02-11 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_available', models.PositiveIntegerField(default=0)),
                ('blood_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.bloodgroup')),
            ],
        ),
    ]
